"""Create two different text files with sample content."""

from pathlib import Path

FILES = {
    "greeting.txt": (
        "Hello from the EMS project!\n"
        "This file was generated by create_files.py.\n"
    ),
    "notes.txt": (
        "Notes\n"
        "=====\n"
        "1. This is the second generated file.\n"
        "2. Its content is different from greeting.txt.\n"
    ),
}


def main() -> None:
    out_dir = Path(__file__).parent
    for name, content in FILES.items():
        path = out_dir / name
        path.write_text(content, encoding="utf-8")
        print(f"Created {path}")


if __name__ == "__main__":
    main()
